### ISSUE TITLE
[Fake 5] Conflict when resolving packages

### ISSUE THREAD

**Issue by Alxandr** [fsharp/FAKE#1564] opened 2017-05-27 22:22 UTC
### Description

I'm trying out fake 5, but it fails when downloading packages.

```
Build failed.
Error:
There was a version conflict during package resolution.
  Conflict detected:
   - Dependencies file requested package Fable.Compiler: 1.0.7
   - Available versions:
     - (1.0.7, [https://api.nuget.org/v3/index.json])
     - (1.0.6, [https://api.nuget.org/v3/index.json])
     - (1.0.5, [https://api.nuget.org/v3/index.json])
     - (1.0.4, [https://api.nuget.org/v3/index.json])
     - (1.0.3, [https://api.nuget.org/v3/index.json])
     - (1.0.2, [https://api.nuget.org/v3/index.json])
     - (1.0.1, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-921, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-920, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-918, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-917, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-916, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-915, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-914, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-912, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-911, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-910, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-909, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-908, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-906, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-905, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-904, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-903, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-9, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-8, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-7, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-6, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-5, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-4, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-3, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-2, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-15, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-10, [https://api.nuget.org/v3/index.json])
     - (1.0.0-narumi-1, [https://api.nuget.org/v3/index.json])
```

I've tried specifying a version, a version range, and leaving it blank.
Also tried with nuget API version 2 and 3.

### Repro steps

build.fsx:

```
(* -- Fake Dependencies paket.dependencies
file ./paket.dependencies
group Build
-- Fake Dependencies -- *)
#load "./.fake/build.fsx/loadDependencies.fsx"
```

paket.dependencies:

```
source https://api.nuget.org/v3/index.json

nuget FSharp.Core redirects:force, content:none
nuget Fable.Core

group Build
  source https://api.nuget.org/v3/index.json
  nuget Fable.Compiler
```

### Expected behavior

It should resolve and download the package.

### Actual behavior

It crashes, with a resolution error.

### Known workarounds

Create the `.paket` folder in the project

### Related information 

* Operating system OSX
* Branch latest pre-release on github (5.0.0-alpha009)
* .NET Runtime, CoreCLR or Mono Version: `Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Fri May 19 14:03:07 BST 2017)` (but should not matter, as I'm not running it)
* Performance information, links to performance testing scripts

**Comment by matthid** [comment] 2017-05-27 23:11
Cannot reproduce, for me this setup works :/

**Comment by matthid** [comment] 2017-05-28 16:24
Edited your issue to add the workaround. Revant if someone stumbles over this issue. You can get paket logging by adding `--verbose` twice.

**Comment by matthid** [comment] 2017-09-22 22:43
I'm closing this as I think this might have been solved by accident with the new `storage: none` option. It should actually work with latest. Please re-test and report back.

**Closed by matthid** 2017-09-22 22:43 UTC

**Comment by matthid** [comment] 2018-02-26 23:57
This took a while to finally be fixed, sorry for that
