### ISSUE TITLE
Caching does not work for scripts in subfolders

### ISSUE THREAD

**Issue by Mpdreamz** [fsharp/FAKE#878] opened 2015-07-23 10:07 UTC
I run my FAKE script like this (from a bat file):

`"build\tools\FAKE\tools\Fake.exe" "build\\scripts\\Targets.fsx"`

and I see no `.fake` folder appearing, however if i change it to:

"build\tools\FAKE\tools\Fake.exe" "build.fsx" I do see the cached dll appearing in `.fake`

**Comment by xavierzwirtz** [comment] 2015-07-23 17:11
I cannot reproduce that behavior, could you give me an example that I can clone that exhibits this?

**Comment by matthid** [comment] 2017-05-06 15:08
I guess we add the `.fake` directory to the working directory or something like that. Feel free to re-open with a repro as this might be a bug. Closing for now.

**Closed by matthid** 2017-05-06 15:08 UTC
