### ISSUE TITLE
Stackoverflow in FSReveal

### ISSUE THREAD

**Issue by jskulavik** [fsharp/FAKE#1124] opened 2016-02-03 08:35 UTC
Hi @forki,

I'm pushing very hard to adopt F# within our enterprise, and am starting with a few efforts, one of which is FsReveal.  That being said, I am relegated to private, non-GitHub hosting of all F# goodies, including FAKE.  

When I execute the build.cmd file on my Windows2012 R2 server I get a stackoverflowexception with the following details:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	FAKE.exe
  Application Version:	4.17.1.0
  Application Timestamp:	56a76f5d
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	54504ade
  Exception Code:	c00000fd
  Exception Offset:	00011a5d
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	c032
  Additional Information 2:	c03216b76b2f537f4af13c470188f853
  Additional Information 3:	af4f
  Additional Information 4:	af4f52e23e698e4ea5b2af606838d7b5

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Any ideas?

Thank you, 
Jarrod

**Comment by forki** [comment] 2016-02-03 08:51
uh. can i reproduce this?

**Comment by jskulavik** [comment] 2016-02-03 14:10
Oh, shame on me, it was a bit late, sorry about that...

To reproduce:

1.  Instantiate a new Windows Server VM 2012 somewhere (I used Azure)
2.  Follow standard 'getting started' instructions for [FsReveal](http://fsprojects.github.io/FsReveal/getting-started.html)
3.  Run build.cmd

**Comment by forki** [comment] 2016-02-03 14:13
Did you try to update .NET framework? Not sure what version you have

**Comment by jskulavik** [comment] 2016-02-03 14:19
4.0, but will check...

**Comment by forki** [comment] 2016-02-03 14:22
That#s pretty old. Try to patch it. I can't remember if we still support
this

2016-02-03 15:19 GMT+01:00 Jarrod Skulavik <notifications@github.com>:

**Comment by jskulavik** [comment] 2016-02-03 15:51
That's not the only thing that's old here...clearly, showing my age. 

After installing .NET 4.6, I get the exact same StackOverflowException :-(

**Comment by forki** [comment] 2016-02-03 16:08
ok we can reproduce

**Comment by jskulavik** [comment] 2016-02-03 16:12
Okay, I'm going to try the same workflow for getting FAKE, Paket, Suave, and FsReveal up and running on Linux too.  Once we sort this out, I'll change and submit a PR to the appropriate documentation spot

**Comment by forki** [comment] 2016-02-03 16:17
this SO looks specific to something Windows2012 R2 does and also fsreveal specifc.
@part-timedev is trying to set up a machine with VS so that we can debug. The machine were we reproduce can't do it.

**Comment by jskulavik** [comment] 2016-02-03 16:20
Would it help if I set up VS on the machine where I'm seeing it and provide you and @part-timedev access?

**Comment by forki** [comment] 2016-02-03 16:21
already pinned it down to FsReveal.GenerateFromFile(file.FullName, outDir, fsiEvaluator = fsiEvaluator)

**Comment by jskulavik** [comment] 2016-02-03 16:22
Ahh, okay.  I'll follow along then.

**Comment by forki** [comment] 2016-02-03 16:27
can you try to checkout the fesreveal develop branch and run build.cmd there?
maybe a unittest already fails.

**Comment by jskulavik** [comment] 2016-02-03 16:39
Here's what that produces:

![fsreveal](https://cloud.githubusercontent.com/assets/2044176/12789177/a4576cba-ca94-11e5-8a82-136ea06c2421.png)

**Comment by forki** [comment] 2016-02-03 16:41
Ok this is shit. Trying to fix this first.

Tbh I think you used the wrong repo for repo. FAKE seems to work fine. But
anyways. Let's try to fix it

**Comment by jskulavik** [comment] 2016-02-03 16:46
OK.  I pulled [this](https://github.com/fsprojects/FsReveal.git) repo and checked out the develop branch.  Is there another repo I should have pulled?

**Comment by jskulavik** [comment] 2016-02-03 16:49
Sorry, you meant the issue.  Let me know if you'd like for me to close it here in FAKE and move it to FsReveal

**Comment by forki** [comment] 2016-02-03 16:50
It seems worse. After installing VS on the VM everything works as expected.

**Comment by jskulavik** [comment] 2016-02-03 16:50
Huh.  MSBuild issue perhaps?

**Comment by forki** [comment] 2016-02-03 16:51
I assume it's a weird .NET framework patch that is installed together with VS 2013

**Comment by forki** [comment] 2016-02-03 16:58
![image](https://cloud.githubusercontent.com/assets/57396/12789809/9e9ef846-ca9f-11e5-919e-b86b401b95d0.png)

@matthid  @tpetricek  is that by any chance FSharp.Formatting related?

**Comment by matthid** [comment] 2016-02-03 17:41
@forki It looks like [this](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L269) but I'm not sure why it doesn't go into the first [case](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L259). At least my eyes cannot spot any difference (but the AssemblyName instances obviously do not equal each other). However the warning is there to notify the user if we redirect some (not matching) versions, so it seems like it's doing what it is supposed to do.

I don't think this is related (but could very well be, maybe this is the difference VS installation is introducing)

**Comment by matthid** [comment] 2016-02-03 17:42
Ah now I see it, the culture is different, but you can rule this out by deleting the fake cache (as without cache this code is not used).

**Comment by forki** [comment] 2016-02-03 18:16
I think the Microsoft.Build.Framework, Version=12.0.0.0, message is unrelated.

After uninstalling VS we get the error back.

**Comment by matthid** [comment] 2016-02-03 18:22
This looks like a FCS/FSharp.Core.sigdata/optdata thing (possibly related to FSF). Any chance to look with process explorer at the loaded dlls and their paths?

Now that we don't use the FCS bundled with FAKE we need to find our own... without installed VS there is probably no working one available.

**Comment by matthid** [comment] 2016-02-03 18:23
Using the one from FAKE had some advantages in those situations (we probably didn't noticed earlier because executing FSF on a non-development environment is unusual)

**Comment by forki** [comment] 2016-02-03 18:28
ha! @matthid bingo! downgrade to FAKE 4.12 solved it. So @jskulavik you were right, it is indeed a FAKE issue.

**Comment by forki** [comment] 2016-02-03 18:29
so how can we solve it?

**Comment by matthid** [comment] 2016-02-03 18:30
Hm I just wanted to post that it should work anyways because we use [`CurrentDomain.BaseDirectory`](https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L105) directory which should resolve to the FSharp.Core bundled with FAKE.... No idea whats going on. I think I need to setup a VM as well :(

**Comment by matthid** [comment] 2016-02-03 23:50
![99 little](http://i.imgur.com/HTisMpC.jpg)

For now I got this (with Debug Diag) :

```
[[PrestubMethodFrame] (Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore$cont@266)] Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore$cont@266(System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, ResolutionEnvironment, System.Tuple`2[], System.String, Microsoft.FSharp.Core.FSharpFunc`2>, Microsoft.FSharp.Core.FSharpFunc`2, Microsoft.FSharp.Core.FSharpFunc`2>, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, Boolean, Microsoft.FSharp.Core.Unit) 
Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore(ResolutionEnvironment, System.Tuple`2[], System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, System.String, Boolean, Microsoft.FSharp.Core.FSharpFunc`2, Microsoft.FSharp.Core.FSharpFunc`2>, Microsoft.FSharp.Core.FSharpFunc`2>)+5b 
Microsoft.FSharp.Compiler.MSBuildResolver.Resolve(ResolutionEnvironment, System.Collections.Generic.IEnumerable`1>, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, System.String, Microsoft.FSharp.Core.FSharpFunc`2, Microsoft.FSharp.Core.FSharpFunc`2>, Microsoft.FSharp.Core.FSharpFunc`2>)+11a 
Microsoft.FSharp.Compiler.CompileOps.Resolve@2941-2(TcConfig, ResolveAssemblyReferenceMode, range, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.Collections.Generic.IEnumerable`1>, Boolean)+11a 
Microsoft.FSharp.Compiler.CompileOps+TcConfig.TryResolveLibsUsingMSBuildRules(TcConfig, Microsoft.FSharp.Collections.FSharpList`1, range, ResolveAssemblyReferenceMode)+439 
Microsoft.FSharp.Compiler.CompileOps+TcImports.TryResolveAssemblyReference(AssemblyReference, ResolveAssemblyReferenceMode)+16f 
Microsoft.FSharp.Compiler.Interactive.Shell+MagicAssemblyResolution.ResolveAssembly(range, TcConfigBuilder, TcImports, FsiDynamicCompiler, FsiConsoleOutput, System.String)+183 
Microsoft.FSharp.Compiler.Interactive.Shell+MagicAssemblyResolution+handler@1561-5.Invoke(System.Object, System.ResolveEventArgs)+36 
mscorlib_ni!System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)+9d 
[[GCFrame]] 
[[PrestubMethodFrame] (Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore$cont@266)] Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore$cont@266(System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, ResolutionEnvironment, System.Tuple`2[], System.String, Microsoft.FSharp.Core.FSharpFunc`2>, Microsoft.FSharp.Core.FSharpFunc`2, Microsoft.FSharp.Core.FSharpFunc`2>, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, Boolean, Microsoft.FSharp.Core.Unit) 
Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore(ResolutionEnvironment, System.Tuple`2[], System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, System.String, Boolean, Microsoft.FSharp.Core.FSharpFunc`2, Microsoft.FSharp.Core.FSharpFunc`2>, Microsoft.FSharp.Core.FSharpFunc`2>)+5b 
Microsoft.FSharp.Compiler.MSBuildResolver.Resolve(ResolutionEnvironment, System.Collections.Generic.IEnumerable`1>, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.String, System.String, System.String, System.String, Microsoft.FSharp.Core.FSharpFunc`2, Microsoft.FSharp.Core.FSharpFunc`2>, Microsoft.FSharp.Core.FSharpFunc`2>)+11a 
Microsoft.FSharp.Compiler.CompileOps.Resolve@2941-2(TcConfig, ResolveAssemblyReferenceMode, range, System.String, System.String, System.String, Microsoft.FSharp.Collections.FSharpList`1, System.Collections.Generic.IEnumerable`1>, Boolean)+11a 
Microsoft.FSharp.Compiler.CompileOps+TcConfig.TryResolveLibsUsingMSBuildRules(TcConfig, Microsoft.FSharp.Collections.FSharpList`1, range, ResolveAssemblyReferenceMode)+439 
Microsoft.FSharp.Compiler.CompileOps+TcImports.TryResolveAssemblyReference(AssemblyReference, ResolveAssemblyReferenceMode)+16f 
Microsoft.FSharp.Compiler.Interactive.Shell+MagicAssemblyResolution.ResolveAssembly(range, TcConfigBuilder, TcImports, FsiDynamicCompiler, FsiConsoleOutput, System.String)+183 
Microsoft.FSharp.Compiler.Interactive.Shell+MagicAssemblyResolution+handler@1561-5.Invoke(System.Object, System.ResolveEventArgs)+36 
mscorlib_ni!System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)+9d 
[[GCFrame]] 

...
```

But I don't know which assembly it's trying to resolve (jet). But with this stack it looks more like a FCS bug than what I described above...

**Comment by jskulavik** [comment] 2016-02-04 05:24
Well, Microsoft.FSharp.Collections.FSharpList shows up a lot.  Does anybody know what that class is?  Perhaps there's something to the Microsoft.FSharp.Collections assembly, no?

**Comment by forki** [comment] 2016-02-04 07:41
Microsoft.FSharp.Collections.FSharpList is standard F# list. That thing is fine.

BTW: if you want to use Fsreveal you can go to the paket.lock file in the root and downgrade FAKE to 4.12 manually. Then the fsreveal should create the slides for you.

The real fix might take a while...

**Comment by tpetricek** [comment] 2016-02-04 12:27
I've seen a big caused by recursive `AssemblyResolve` invocations before in the R provider....

 * Issue details: https://github.com/BlueMountainCapital/FSharpRProvider/issues/97
 * Fix: https://github.com/BlueMountainCapital/FSharpRProvider/pull/101
 * Code with all the workarounds: https://github.com/BlueMountainCapital/FSharpRProvider/blob/257930c658dbf7220633816cf41a6f0e41e321d7/src/RProvider/Configuration.fs#L62

The stack trace looks different, so perhaps this isn't related. 

The best lesson I learned in the above issue was that adding logging (to discover which assembly load was recursively triggered) caused yet another recursive load. All was related to loading those weird `resources` assemblies.

**Comment by matthid** [comment] 2016-02-04 19:03
A custom FAKE build prints:

```
trying to resolve FSharp.CodeFormat, Version=2.13.5.0, Culture=neutral, PublicKeyToken=null
trying to resolve FSharpVSPowerTools.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null
trying to resolve Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
trying to resolve Microsoft.Build.Tasks.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
...
```
@forki Maybe FAKE should bundle this if FCS depends on it?

**Comment by forki** [comment] 2016-02-04 19:08
bundle what? Microsoft.Build.Tasks.v12.0 and Microsoft.Build.Tasks.v12.0?

**Comment by matthid** [comment] 2016-02-04 19:10
I'm still experimenting, but yes that's what I meant

**Comment by forki** [comment] 2016-02-04 19:10
how big is this stuff? and do we have "license" tio bundle it?

**Comment by tpetricek** [comment] 2016-02-04 19:17
This looks like a case of https://github.com/fsharp/FSharp.Compiler.Service/issues/337. 

@rneatherway says it should be fixed now, but perhaps FCS still has a MSBUILD dependency? Is FAKE using the more recent 4.x versions? I think it should be solved there...

**Comment by matthid** [comment] 2016-02-04 19:17
It's 1MB. I'm not a lawer :) / don't know.
I verified that bundling solves the problem, but I'm not sure if this the correct fix

**Comment by tpetricek** [comment] 2016-02-04 19:20
I think this is really a FCS bug, it should be solved there...

**Comment by matthid** [comment] 2016-02-04 19:23
@tpetricek yeah, we probably need to update FAKE's and FSF's dependencies, because it could be triggered by the FSF FCS dependency as well (as FAKE is already on a pretty recent 2.x version IIRC)

**Comment by forki** [comment] 2016-02-04 19:23
https://github.com/fsharp/FAKE/blob/master/paket.lock#L19

**Comment by forki** [comment] 2016-02-04 19:24
https://github.com/fsharp/FAKE/blob/master/paket.lock#L102

lol we have two ;-)

**Comment by tpetricek** [comment] 2016-02-04 19:51
whoa

**Comment by matthid** [comment] 2016-02-04 20:05
Ok it's definitely fsharp/FSharp.Compiler.Service#337 I was a bit caught off-guard of why my initial approach of attaching to the AssemblyResolve event (for debugging) did not work and I was forced to patch FAKE. But the reason is that FSReveal initializes an Evaluator, which will subscribe the `magic` handler earlier than I thought.

This will be fixed with the next FSF update (once we update to a not-broken FCS version).

**Comment by forki** [comment] 2016-02-04 20:10
I guess that's one of the issues that you get with circle of trust. ;-)

Anyways. So strategy is: update FSC in fsf. Update fsf in fake. Update
everything in fsreveal. Right?

**Comment by matthid** [comment] 2016-02-04 20:12
Yes, but I don't think `Update fsf in fake.` is actually required.

**Comment by forki** [comment] 2016-02-04 20:18
yeah. right.

**Comment by jskulavik** [comment] 2016-02-04 20:21
Wow gents, wow.  Well I'm very happy to have stumbled upon this and that you all understand the issue.  I'm still getting up to speed with F# itself, so my ability to contribute code will be limited for a short while as I get ramp up.  However, my master plan, as noted in the root post of this issue, is to "do everything in F#" from prezos (FsReveal) to web, (Suave/aspnet) to build (FAKE), to big data (MBrace), to AKKA.NET, to compute on ServiceFabric(https://gist.github.com/isaacabraham/601d058df22ac6c26c64).  This was my first step in that direction, and I'm planning to keep marching full steam ahead.

**Comment by matthid** [comment] 2016-02-04 20:26
@jskulavik Glad to hear, happy F#ing :)

```
.paket/paket.exe update
```
Will now fix the issue (https://www.nuget.org/packages/FSharp.Formatting/2.14.0).

**Comment by jskulavik** [comment] 2016-02-04 20:27
Thanks @matthid.  I'll give that update a go now...

**Comment by forki** [comment] 2016-02-04 20:30
@jskulavik you just have been extremly unlucky here. Hope that this will not stop you from exploring more of the ecosystem. As you can see many people care about it. ;-)

**Comment by jskulavik** [comment] 2016-02-05 00:02
It's no problem at all @forki, honestly.  I'm excited to finally be underway.  As for the community, I'm doing my best to spread he love here with the foundation, hosting meetups and planning some hacking.  All good with me F#ing!

**Comment by forki** [comment] 2016-02-05 08:32
I just saw the new release of FSF and tried to paket update in fsreveal. Now the fsreveal develop build fails:

![image](https://cloud.githubusercontent.com/assets/57396/12841336/65db5322-cbeb-11e5-81db-07a307d202fb.png)

**Comment by matthid** [comment] 2016-02-05 08:52
Interesting, paket update worked on my win server test machine

**Comment by forki** [comment] 2016-02-05 08:54
the update worked. but the build afterwards runs in missingmethodexeption

**Comment by forki** [comment] 2016-02-05 08:54
(in develop branch of fsreveal)

**Comment by tpetricek** [comment] 2016-02-05 09:33
This is most likely because of Visual F# PowerTools (cc @dungpa @vasily-kirichenko). F# Formatting is calling VFPT.Core to get nicer colorization.

I think NuGet packages for VFPT.Core have dependency on FCS that says `>= [the version that was used when building the release]` but FCS changes its API more often and so  VFPT only really works with `= [the version that was used when building the release]`. 

There is a work in progress PR for VFPT to update it to the latest FCS, but I'm not sure what's the status.

**Comment by tpetricek** [comment] 2016-02-05 09:36
(Maybe we should just copy/reimplement the nice colorization from VFPT and put it directly into FSF, this has been causing way too many issues...)

**Comment by matthid** [comment] 2016-02-05 10:20
I think FCS tries to follow semver now so if it breaks because of fcs changes its a fcs bug... (because dependencies in fsf are correct)

**Comment by dungpa** [comment] 2016-02-05 13:32
@tpetricek I published VFPT.Core 2.3.0 and notified you a few days ago https://github.com/fsprojects/VisualFSharpPowerTools/pull/1317#issuecomment-177276571

**Comment by tpetricek** [comment] 2016-02-05 15:51
@dungpa Fantastic, thanks, sorry for missing that!

**Comment by matthid** [comment] 2016-02-05 20:53
@forki I cannot reproduce. It was working for me besides some FSharp.Core issues: https://github.com/fsprojects/FsReveal/pull/94

**Comment by forki** [comment] 2016-02-06 09:09
Thanks everyone for helping to kill this one.

![squash](https://cloud.githubusercontent.com/assets/57396/12865858/4bc9e754-ccb9-11e5-8721-8a3a3a47c331.gif)

![image](https://cloud.githubusercontent.com/assets/57396/12865864/b2d52d6e-ccb9-11e5-95b9-328a29f46b75.png)

**Closed** 2016-02-06 09:09 UTC
Labels: bug

**Comment by jskulavik** [comment] 2016-02-06 09:18
#Beautiful
