### ISSUE TITLE
Using paket wrapper as local tool, it doesn't issue command

### ISSUE THREAD

**Issue by TheAngryByrd** [fsharp/FAKE#2414] opened 2019-10-21 20:40 UTC
### Description

When trying to use paket wrapper as a [localtool](https://github.com/fsharp/FAKE/pull/2399/files), it doesn't seem to add the actual command to the shell.

### Repro steps

Please provide the steps required to reproduce the problem

For example given this code (this can also be reproduced with restore instead of push):

```fsharp
    Paket.push(fun c ->
        { c with
            ToolType = ToolType.CreateLocalTool()
            PublishUrl = publishUrl
            WorkingDir = "dist"
        }
    )
```

This shells out with this output:

```bash
dist> "/usr/local/share/dotnet/dotnet" paket --url https://www.nuget.org MyLibrary/dist/MyLibrary.1.0.1.0.nupkg (In: false, Out: false, Err: false)
ERROR: unrecognized argument: '--url'.
```
### Expected behavior

It should also have `push` in the output. so:

```
dist> "/usr/local/share/dotnet/dotnet" paket push --url https://www.nuget.org MyLibrary/dist/MyLibrary.1.0.1.0.nupkg
```

### Actual behavior

```bash
dist> "/usr/local/share/dotnet/dotnet" paket --url https://www.nuget.org MyLibrary/dist/MyLibrary.1.0.1.0.nupkg (In: false, Out: false, Err: false)
ERROR: unrecognized argument: '--url'.
```

### Known workarounds

n/a

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Indications of severity
* Version of FAKE (4.X, 5.X)
* (if performance issue) Performance information, links to performance testing scripts

**Comment by matthid** [comment] 2019-10-21 20:54
Yes an unfortunate duplicate of https://github.com/fsharp/FAKE/issues/2411, I'm working on it

**Closed by matthid** 2019-10-21 20:54 UTC
