### ISSUE TITLE
Fake.Deploy 

### ISSUE THREAD

**Issue by simax** [fsharp/FAKE#1390] opened 2016-09-29 15:13 UTC
I'm getting: 

`error FS0078: Unable to find the file c:\Windows\system32\deployments\mfw\active\deploy.fsx' in any of c:\windows\system32` 

When I use the following command

```
Fake.Deploy /deployRemote http://89.120.12.67:8080/fake ./mfw.nupkg
```

But when I look on the remote machine, the file `'C:\Windows\system32\deployments\mfw\active\deploy.fsx'` does exist.

The `mfw.nupkg` package is a web application with `deploy.fsx` in the root of the folder.

Any idea why I'm getting this error?

**Comment by ditadi** [comment] 2016-11-16 19:58
It seems that working directory somehow defaults to C:\Windows\system32.  I found that setting my own working directory in configuration of Fake.Deploy.exe resolves this issue.

Example: `FAKE/tools/Fake.Deploy.exe `and changing working directory to `C:\YourWorkingDirectory` instead of `.`

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="ServerName" value="localhost" />
    <add key="Port" value="*" />
    <add key="WorkDirectory" value="C:\YourWorkingDirectory" />
    <add key="LogDirectory" value="~/log" />
    <add key="Authorization" value="Off" />
    <add key="AuthorizedKeysFile" value="~/.ssh/authorized_keys" />
    <!--
    <add key="Authorization" value ="On" />
    <add key="AuthorizedKeysFile" value="..\..\..\..\test\Test.Fake.Deploy\TestData\authorized_keys" />
    -->
  </appSettings>
```

**Comment by matthid** [comment] 2017-05-07 01:02
Any idea how to reproduce this (step by step)? Closing until we have reproduction steps. This looks like a bug.

**Closed by matthid** 2017-05-07 01:02 UTC
