### ISSUE TITLE
Xml.PokeInnerText mangles DOCTYPE definition

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1692] opened 2017-09-29 01:20 UTC
### Description

In migrating to FAKE 5, I've switched from `XmlPokeInnerText` to `Xml.PokeInnerText`. However, the result is that my XML is now left in an invalid state:

BEFORE:
```XML
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

AFTER:
```XML
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"[]>
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Update an XML file that has a `DOCTYPE` definition using `Xml.PokeInnerText`

### Expected behavior

Should act same as old `XmlPokeInnerText`.

### Actual behavior

Breaks the XML.

### Known workarounds

Use old API.

**Comment by matthid** [comment] 2017-09-30 13:02
Can you provide a minimal XML sample and the `PokeInnerText` call? I feel like this could be a framework but as I cannot recall any code changes there. Though the `[]` look quite suspicious to an empty list being printed so I'd like to reproduce that locally before reporting to the corefx team.

**Comment by kentcb** [comment] 2017-10-02 22:23
Here's some example XML (_Info.plist_):
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>foo</string>
</dict>
</plist>
```
Here's an example target:
```F#
Target.Create "testing" (fun _ ->
    let plist = srcDir @@ "UI.iOS/Info.plist"
    let bundleIdentifier = "whateva"
    Xml.PokeInnerText plist "plist/dict/key[text()='CFBundleIdentifier']/following-sibling::string" bundleIdentifier
)
```
And here's the (invalid) output:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"[]>
<plist version="1.0">
  <dict>
    <key>CFBundleIdentifier</key>
    <string>whateva</string>
  </dict>
</plist>
```

**Comment by matthid** [comment] 2018-05-19 21:13
This is kind of an unfortunate side-effect of using `XmlDocument`:
- https://stackoverflow.com/a/16451790
- https://stackoverflow.com/questions/284394/net-xmldocument-why-doctype-changes-after-save

I changed it in a way that without `[]` is always preferred but realistically that might break people who expect `[]`, unfortunately it seems to be quite hard to leave it as-is.
So this should be fixed with RC015

**Closed by matthid** 2018-05-19 21:13 UTC
Labels: bug, help wanted
