### ISSUE TITLE
Finding dotnet binary location

### ISSUE THREAD

**Issue by TheAngryByrd** [fsharp/FAKE#1961] opened 2018-05-22 15:54 UTC
### Description

I'm working on a system where I have dotnet installed via the graphic installers (under `/usr/local/share/dotnet`. However sometimes F# libraries have been trying to bootstrap dotnet by installing it under `{userFolder}/.dotnet`.  So I have a bunch of sdks installed in two different folders.

When FAKE goes to look for dotnet it prefers the`{userFolder}` one. 
https://github.com/fsharp/FAKE/blob/master/src/app/Fake.DotNet.Cli/DotNet.fs#L35-L43

I'm thinking this logic should be flipped, it should prefer PATH then fallback to the userfolder.  Instead of choosing the `{userFolder}` first. 

### Related information 

* Operating system
MacOS

**Comment by matthid** [comment] 2018-05-22 16:13
Afaik we just look through PATH. just like any other tool using PATH does

**Comment by baronfel** [comment] 2018-05-22 16:15
No, the link shows that we first probe for `{userFolder}/.dotnet/dotnet`, which could exist if one of these old scripts has run.  We should prefer PATH.

**Comment by matthid** [comment] 2018-05-22 16:17
You did specify an SDK version in your build-script, correct? (Such that fake installs the correct version if needed)

**Comment by baronfel** [comment] 2018-05-22 16:32
really though I think the root of the problem is that the default installation directory for linux doesn't match up with what the official SDK install packages set by default. If they lined up then the current tryFind logic should work

**Comment by matthid** [comment] 2018-05-22 16:34
> no, because that should be the use of the global.json file, so that when users run dotnet commands from the repo the correct version is used.

That one is really disturbing behavior at least last time I tried. This makes working across different repositories with different sdk versions a HUGE pain. That's why I removed that. Have they fixed that?

**Comment by matthid** [comment] 2018-05-22 16:36
And in reality you don't care too much locally and are fine with using a more recent version locally. You just want to ensure that the build-server uses the version specified (at least that's how I feel about it)

**Comment by baronfel** [comment] 2018-05-22 16:38
Can you speak more to the kinds of issues you found? We've got different sdk versions here at work and if you don't have the proper sdk version installed you get an error. Dotnet SDK versions 2.0.0 and greater made this change: https://github.com/dotnet/sdk/issues/1470#issuecomment-322318135

**Comment by matthid** [comment] 2018-05-22 16:42
> if you don't have the proper sdk version installed you get an error.

That is the problem. You have one sdk installed and two projects, if you switch context you need to install another version oO Maybe I just don't get it but this is really frustrating.

Locally I'm fine with using my 2.1-alpha version if global.json specifies 2.0 but not on the build server.

The reason why I'm asking for this is because I don't think fixing this issue is simply changing the code statements. Because then others will complain

**Comment by baronfel** [comment] 2018-05-22 16:42
for posterity: the default locations for the dotnet sdk now are:

* Unix -> `/usr/local/share/dotnet/dotnet`
* Windows -> `C:\Program Files\dotnet\dotnet.exe`

**Comment by matthid** [comment] 2018-05-22 16:45
I think the fix might be to search all paths, return a list and then when we check the version (ie we could read global.json if not specified in the build script) consider all installations and take the first that fits. But that is probably a bit larger than this suggestion

**Comment by baronfel** [comment] 2018-05-22 16:45
> Locally I'm fine with using my 2.1-alpha version if global.json specifies 2.0 but not on the build server.

See I'm not though. Shouldn't the build server and the local dev environment be the same? And is having multiple SDK copies really a bad thing? If nothign else as projects are moved up/upgraded you can purge the old folders. The bulk of the space is the nuget package cache anyway, and that's cross-SDK-version.

**Comment by baronfel** [comment] 2018-05-22 16:48
@matthid I think we get to a 'good enough' solution right now if we update the default locations to point to the ones above. What is your opinion?

**Comment by matthid** [comment] 2018-05-22 16:52
@baronfel Just to understand this correctly:

How do you switch your dotnet between the repositories? Are you using the full path to use the correct version?

In repository 1
```
$ /dotnetsdk2.0/dotnet build my.proj
```

In repository 2
```
$ /dotnetsdk2.1/dotnet build my.proj
```

Or somehow switch around PATH?

Because if you just use `$ dotnet` it can only have a single version and therefore only work on a single project

**Comment by baronfel** [comment] 2018-05-22 17:03
That's not quite the case.  The `dotnet` binary at the install path is a version-switcher. It looks at a `global.json` file (if present) and attempts to run the sdk for that version. If no `global.json` is found, it delegates to the highest installed version present. The default probing location for SDKs is `path/to/dotnet/binary/../sdks/`.

so for example on my machine I have the following sdks installed:
```
1.0.4 [/usr/local/share/dotnet/sdk]
2.0.0 [/usr/local/share/dotnet/sdk]
2.1.4 [/usr/local/share/dotnet/sdk]
2.1.101 [/usr/local/share/dotnet/sdk]
2.1.200 [/usr/local/share/dotnet/sdk]
```

when I run `dotnet XXXX` in project A, I use dotnet sdk 2.0.0, because the global json for that project pins to 2.0.0.

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/
```

when I run `dotnet xxx` in project B, I get a different version of the sdk, because the global.json in that project has pinned to 2.1.200

```
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.200/
```

this ensures that locally and on the build server we all use the same versions, even if the build server/local machines have many sdks.

**Comment by baronfel** [comment] 2018-05-22 17:07
And for comparison, here's the error you get when you don't have the desired dotnet SDK installed:
```
A compatible SDK version for global.json version: [2.2.400] from [/Users/chethusk/work/server/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by matthid** [comment] 2018-05-22 17:12
Ah thanks. And I guess we cannot trigger or influence that "magic" from the outside, correct?

**Comment by matthid** [comment] 2018-05-22 17:14
And when using the script-installer (the one fake uses) does that one also have the version switcher as you call it?

**Comment by baronfel** [comment] 2018-05-22 17:28
Looking at it, the path to the sdk is `{base_dotnet_dir}/sdk/{sdk_version}/dotnet.dll`, and the 'version-switcher' app is the runtime host that picks the version dll to use and then effectively runs `dotnet {base_dotnet_dir}/sdk/{sdk_version}/dotnet.dll` (ie self-invoking?)

**Comment by kblohm** [comment] 2018-05-22 17:28
I am pretty sure after installing with with the script, fake just points to the version switcher. And the switcher then uses the newest version. (At least that was the case on windows if i remember correctly)

**Comment by baronfel** [comment] 2018-05-22 17:29
@kblohm yes, because the version-switcher that was installed at that directory only has the one version in its `sdk` folder.

**Comment by matthid** [comment] 2018-05-22 17:34
> If we continue to use the scripts I would suggest setting the install parameter to the system default directory 

I'm not sure if this is a good idea. Would this just ADD and sdk or MODIFY the global installation?
If it only adds a version we additionally need to ensure to write `global.json` before calling `dotnet` because otherwise we might not get the version specified in the build script (in case you specify your version in fake)

**Comment by matthid** [comment] 2018-05-22 17:36
Also you probably don't have enough access to write to install directory.

**Comment by matthid** [comment] 2018-05-22 17:41
To get back to this issue:

> I'm thinking this logic should be flipped, it should prefer PATH then fallback to the userfolder. Instead of choosing the {userFolder} first.

Can someone also clarify what the actual problem is? Is it that the version you are trying to use is only available in the global installation?

**Comment by baronfel** [comment] 2018-05-22 17:44
Yeah. The issue as written now doesn't make sense, given that we allow for path overrides. The current logic for discovering the path is fine, just now I disagree with the default sdk locations :D

**Comment by kblohm** [comment] 2018-05-22 18:43
@baronfel Yes you are right. 
Right now the version installed with `DotNet.install` is not used in `DotNet.{exec}` anyways, at least on my computer. So that is already either a bug or `DotNet.install` should probably not return a function that suggests you can use it to force the just installed version to be used.

**Comment by baronfel** [comment] 2018-05-22 18:53
I think that would be reasonable. If @matthid is ok with that I'll do a PR for it. Bonus points for using the existing global.json if present to power other calls like asking for the dotnet sdk version.

**Comment by baronfel** [comment] 2018-05-22 19:04
for that case, yes, but I would highly suggest that we change the scripts to install to the now-default paths (the ones I listed above). Then all the paths could be unified. Matthid makes a great point about permissions though, that some users may not be able to install to `C:\program files` or `/usr/local/share` depending on OS

**Comment by kblohm** [comment] 2018-05-22 19:10
So change the default of `CustomInstallDir` to something more appropriate and let the user change it when he needs to?

**Comment by baronfel** [comment] 2018-05-22 19:15
This change essentially (for the paths only):

```
diff --git a/src/app/Fake.DotNet.Cli/DotNet.fs b/src/app/Fake.DotNet.Cli/DotNet.fs
index 626983d80..024d9a440 100644
--- a/src/app/Fake.DotNet.Cli/DotNet.fs
+++ b/src/app/Fake.DotNet.Cli/DotNet.fs
@@ -21,26 +21,25 @@ open System.Text
     open Newtonsoft.Json.Linq
     open System

-    /// .NET Core SDK default install directory (set to default localappdata dotnet dir). Update this to redirect all tool commands to different location.
+    /// .NET Core SDK default install directory (set to default SDK installer paths (/usr/local/share/dotnet or C:\Program Files\dotnet)). Update this to redirect all tool commands to different location.
     let internal defaultDotNetCliDir =
         if Environment.isUnix
-        then Environment.environVar "HOME" @@ ".dotnet"
-        else Environment.environVar "LocalAppData" @@ "Microsoft" @@ "dotnet"
+        then "/usr/local/share/dotnet"
+        else @"C:\Program Files\dotnet"
```

**Comment by matthid** [comment] 2018-05-22 19:26
No need to wait for me for small stuff, we can discuss in pr if needed which makes it clearer anyway

Will take an in depth look later or tomorrow

**Comment by baronfel** [comment] 2018-05-22 19:29
Will do, thanks for the input @matthid and @kblohm. Lemme get a PR going and we can pick it up from there.

**Comment by matthid** [comment] 2018-05-22 21:34
> Right now the version installed with DotNet.install is not used in DotNet.{exec} anyways, at least on my computer. So that is already either a bug or DotNet.install should probably not return a function that suggests you can use it to force the just installed version to be used.

@kblohm For me it is working, but it might in fact be related to the switching logic @baronfel explained above. I bet if you delete your HOME/.dotnet folder it works.

> that goes back to the split between what FAKE sets up and what the PATH sees

But if we want FAKE to behave like command line we would prefer PATH, but we want fake to take the version I specify on "DotNet.install" (if one is specified). But I'm pretty sure we can get this working. Your PR is a good start.

I'm pretty sure now we can track this down now.

**Comment by kblohm** [comment] 2018-05-23 07:46
Also somewhat relevant:
for checking installed versions `dotnet --list-sdks` (new in > 2.1.0-preview1)

**Comment by matthid** [comment] 2018-05-23 08:33
@kblohm yes exactly. we just didn’t know this was possible ;)
But what I’m trying to say is that the returned function is working. I executes the correct binary. that binary is just doing the wrong thing. There is no other binary to execute and the user could not net a “better” toolpath. We can only get the correct version by temporarily writing global.json it seems

**Comment by matthid** [comment] 2018-06-11 21:02
Closing this as PR is already open, we just need to finalize it.

**Closed by matthid** 2018-06-11 21:02 UTC
Labels: enhancement, help wanted
