### ISSUE TITLE
Use Case: Switching between WSL and Windows breaks `intellisense_lazy.fsx`

### ISSUE THREAD

**Issue by varon** [fsharp/FAKE#2345] opened 2019-06-30 00:28 UTC
### Description

Running the build system under WSL results in package paths in `intellisense_lazy.fsx` that point to my home folder in WSL:

`#r "/home/varon/.nuget/packages/system.io.filesystem.watcher/4.3.0/lib/net46/System.IO.FileSystem.Watcher.dll" `

Rider cannot find them, and thus intellisense fails to work.

If instead FAKE is run without WSL, our paths are completely different:

`#r "C:\\Users\\varon\\.nuget\\packages\\system.io.filesystem.watcher\\4.3.0\\lib\\net46\\System.IO.FileSystem.Watcher.dll" `

It would be great if we could still build under WSL and have intellisense work normally afterwards. 

--

**Is there a way to use relative, local references inside the packages folder instead of the magical global locations?**

### Related information 

* W10
* .Net Core 2.2
* Severity: Inconvenience
* 5.X

**Comment by matthid** [comment] 2019-06-30 02:39
I'm not aware of any solution to this. In fact I suggest using Ionide (vscode) for editing FAKE scripts. It has more features and it doesn't have this issue. I will update the docs shortly, as more features will flow into Ionide...

**Comment by matthid** [comment] 2019-06-30 02:47
So IMHO the real solution is to add proper support to the editors, as FAKE support is now available via LSP in fsac. Once editors support that we can even remove the intellisense file. I consider this a tooling issue.

**Comment by varon** [comment] 2019-06-30 12:53
The problem is that we're producing absolute UNIX-style paths instead of cross-platform relative paths.

Trying to resolve `/home/.../...` on windows makes no sense.

**Comment by matthid** [comment] 2019-06-30 13:28
@varon There is no way to generate relative paths into the home directory (where the `.nuget/Packages` folder lives). I'm not sure what we should generate here or what your expectation is.

In fact if you use `storage:packages` ie have the packages folder generated along the FAKE script we already create relative paths.

**Comment by varon** [comment] 2019-06-30 15:07
Ah that's helpful. Any chance that could be made the default?

**Comment by matthid** [comment] 2019-06-30 15:24
No, because it is quite a lot slower and uses more hard-drive space ;)

**Comment by varon** [comment] 2019-06-30 17:44
That's fair enough. Is it possible to do some kind of conditional check or workaround to allow WSL to work?

**Comment by matthid** [comment] 2019-06-30 17:57
Have you tried vscode/ionide?

**Comment by varon** [comment] 2019-06-30 18:31
Main thing is that it's a huge gotcha to run the build on WSL (which builds perfectly) then have the cached pathing (permanently) break intellisense.

The only "fix" from that stage is to manually delete `.fake` directory and re-run the build via `cmd/powershell`.

I tried using `storage:packages` at the top of the FAKE script, but the whole thing exploded in vague failure and misery.

**Comment by matthid** [comment] 2019-06-30 18:34
Ionide tooling shouldn't depend on intellisense files at all, therefore it doesn't have this problem...

**Comment by matthid** [comment] 2019-06-30 18:37
> I tried using storage:packages at the top of the FAKE script, but the whole thing exploded in vague failure and misery.

The proper way to reproduce would be appreciated. Have you deleted the `.lock`-file and the `.fake` folder?

**Comment by varon** [comment] 2019-06-30 18:54
Yeah, it's for use in [OpenTK](https://github.com/opentk/opentk), a primarily C# project. So Rider/VS is the order of the day.  One of the major benefits of FAKE is that contributors don't need to install fancy editors or plugins for it to work out of the box.

You can find a reproduction at [this commit](https://github.com/varon/opentk/tree/571f56d82ea6acd358f0f09ce172b199c776150a).

### Repro steps are:

1) run `./build.sh` on WSL
2) Open the project in rider
3) Watch the world burn

**Comment by matthid** [comment] 2019-06-30 19:10
WSL really is a "fancy" environment. Especially how you use it. I feel like this shouldn't really hit any contributor of [OpenTK](https://github.com/opentk/opentk).
Either staying "within" the WSL as well as staying "outside" of it should work just fine.

Given your usage, you just should use an editor that supports you. Is there any particular reason you are using the WSL and have the need to switch back and forth? Why don't you run fake outside of it?

Note that you don't NEED Ionide not do you NEED to tell your contributors about it. Usually Rider/VS works just fine but for your use case I don't see how it could work.

Another workaround might be having two scripts `build.fsx` and `build_wsl.fsx` and one `#load`ing the other. Just execute one on windows and the other one only in wsl.

**Comment by varon** [comment] 2019-06-30 19:54
I appreciate all of the help and time on this.

The main goal is to keep things simple and compatible. I'd like contributors to just run `./build.sh` or `./build.cmd`. This works fantastically on all platforms, even WSL.

The issue is more philosophical than practical. The mechanism through which packages are referenced shouldn't be dependent upon the cached results which _implicitly_ rely on the specific environment used to perform the (first) build.

For a lot of developers WSL basically just offers a far more convenient shell than powershell, all else being equal. Almost all netcore workflows supports swapping between the two.

Hope that helps clarify a bit?

**Comment by matthid** [comment] 2019-06-30 21:37
Internally we write all cache files more or less platform independent, but this particular file we write for the IDE and the IDE doesn't understand variables or anything. So the following workflow can never work:

- run script in WSL command line
- edit script in Editor without native FAKE support outside of WSL (VS/Rider)

And this is not really because we don't want to. This is because of several limitations in the tooling as of today. Any ideas on how to make it work or what we could do to workaround are appreciated. The best workaround for this workflow is to run `fake build` again outside of the WSL before opening the editor (which is probably not what you want).

> For a lot of developers WSL basically just offers a far more convenient shell than powershell

I'd suggest trying Cygwin or the `git bash` (which is what I'm using)

**Comment by drk-mtr** [comment] 2019-08-16 12:41
I am with Matt on this - this is an editor concern not something that Fake can do.

If you try WSL in VSCode (https://code.visualstudio.com/docs/remote/wsl), you'll see how this would work in practice. Essentially you run a server on the Linux side and the Windows VSCode instance communicates with this. This makes perfect sense to me - I wouldn't expect an editor in one operating system to work seamlessly with an application built under a different kernel.

I would suggest trying to use this sort of remote debugging based approach: https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-clion.html

**Comment by matthid** [comment] 2019-08-17 11:01
I'm closing this as I have no idea at all how we could "fix" this particular behavior. I'm still open to concrete suggestions.

**Closed by matthid** 2019-08-17 11:01 UTC
Labels: discussion, enhancement
