### ISSUE TITLE
Possible caching issue resolving targets from different project

### ISSUE THREAD

**Issue by Mpdreamz** [fsharp/FAKE#1454] opened 2017-01-18 22:32 UTC
In the process of converting a 6 year old project over to Paket and FAKE witnessed a behaviour i can not fully explain.

**greenfield targets.fsx**
```
#I @"../packages/build/FAKE/tools" 
#r @"FakeLib.dll"
open System
open Fake 

Target "Build" <| fun _ -> traceHeader "STARTING BUILD"

"Build"

RunTargetOrDefault "Build" 
```

Output of `packages\build\FAKE\tools\FAKE.exe build\Targets.fsx -lt`

```
Available targets:
  - Build
     Depends on: []
System.Exception: Target "quick" is not defined.
   at Fake.TargetHelper.getTarget@77-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 77
   at Fake.TargetHelper.visitDependenciesAux@352[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, HashSet`1 visited, List`1 ordered, Int32 level, Tuple`2 tupledArg) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 353
   at Fake.TargetHelper.visit@349-1[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 359
   at Fake.TargetHelper.visitDependencies(FSharpFunc`2 fVisit, String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 363
   at Fake.TargetHelper.run$cont@511(String targetName, Unit unitVar) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 551
   at Fake.TargetHelper.run(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 511
   at Fake.AdditionalSyntax.RunTargetOrDefault(String defaultTarget) in C:\code\fake\src\app\FakeLib\AdditionalSyntax.fs:line 29
   at <StartupCode$FSI_0005>.$FSI_0005_Targets$fsx.main@() in c:\Projects\tabalt\build\Targets.fsx:line 10
Stopped due to error
```

The only explanation I have for quick is [a cached target from a different project](https://github.com/elastic/elasticsearch-net/blob/master/build/scripts/Targets.fsx#L28) but even running with `--nocache` yields the same.

Calling parameterless yields much of the same:

```
$ packages\build\FAKE\tools\FAKE.exe build\Targets.fsx
```

AND

```
$ packages\build\FAKE\tools\FAKE.exe build\Targets.fsx -nc
```

yield:

```
Building project with version: LocalBuild
The following targets are available:
   Build
Target "quick" is not defined. Existing targets:
  - Build

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
No target was successfully completed
---------------------------------------------------------------------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Target "quick" is not defined.
   at Fake.TargetHelper.getTarget@77-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 77
   at Fake.TargetHelper.visitDependenciesAux@352[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, HashSet`1 visited, List`1 ordered, Int32 level, Tuple`2 tupledArg) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 353
   at Fake.TargetHelper.visit@349-1[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 359
   at Fake.TargetHelper.visitDependencies(FSharpFunc`2 fVisit, String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 363
   at Fake.TargetHelper.run$cont@511(String targetName, Unit unitVar) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 551
   at Fake.TargetHelper.run(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 511
   at Fake.AdditionalSyntax.RunTargetOrDefault(String defaultTarget) in C:\code\fake\src\app\FakeLib\AdditionalSyntax.fs:line 29
   at <StartupCode$FSI_0005>.$FSI_0005_Targets$fsx.main@()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Fake.FSIHelper.runScriptCached@313.Invoke(Unit unitVar0) in C:\code\fake\src\app\FakeLib\FSIHelper.fs:line 321
System.Exception: Target "quick" is not defined.
   at Fake.TargetHelper.getTarget@77-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 77
   at Fake.TargetHelper.visitDependenciesAux@352[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, HashSet`1 visited, List`1 ordered, Int32 level, Tuple`2 tupledArg) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 353
   at Fake.TargetHelper.visit@349-1[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 359
   at Fake.TargetHelper.visitDependencies(FSharpFunc`2 fVisit, String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 363
   at Fake.TargetHelper.run$cont@511(String targetName, Unit unitVar) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 551
   at Fake.TargetHelper.run(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 511
   at Fake.AdditionalSyntax.RunTargetOrDefault(String defaultTarget) in C:\code\fake\src\app\FakeLib\AdditionalSyntax.fs:line 29
   at <StartupCode$FSI_0005>.$FSI_0005_Targets$fsx.main@() in c:\Projects\tabalt\build\Targets.fsx:line 10
Stopped due to error
```

The only thing that works is: 

```
$ packages\build\FAKE\tools\FAKE.exe build\Targets.fsx build -nc
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build

The resulting target order is:
 - Build
Starting Target: Build

---------------------------------------------------------------------
STARTING BUILD
---------------------------------------------------------------------
Finished Target: Build

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Build      00:00:00.0042895
Total:     00:00:00.0751545
Status:    Ok
---------------------------------------------------------------------
````

Renaming `Targets.fsx` in the project I am converting also has no effect on breaking the cache.

**Comment by Mpdreamz** [comment] 2017-01-19 09:12
old project 

```
$ packages\build\FAKE\tools\FAKE.exe --version
FakePath: c:\Projects\tabalt\packages\build\FAKE\tools\FakeLib.dll
FAKE - F# Make "4.50.0"
```

project that has a `quick` target

```
$ packages\build\FAKE\tools\FAKE.exe --version
FakePath: c:\Projects\elastic\net-master\packages\build\FAKE\tools\FakeLib.dll
FAKE - F# Make "4.47.1"
```

I also tried to move my old project `tabalt` to a completely different tree under `C:\Projects2` but to no avail.

**Comment by matthid** [comment] 2017-01-19 21:05
@Mpdreamz Any Step by Step guide for me to reproduce this?
This might be a caching error. The weird behavior with `-nc` might be because of our quirk legacy command line.

**Comment by Mpdreamz** [comment] 2017-01-19 21:44
Nothing isolated just yet, I could try tomorrow to get something going. 

If you clone https://github.com/elastic/elasticsearch-net and run `build` from the root once and then create a folder with a similar distance to the previous clone with the barebones fsharp targets script in my original post does that work for you?

**Comment by matthid** [comment] 2017-05-07 01:29
Closing until we can reproduce

**Closed by matthid** 2017-05-07 01:29 UTC
