### ISSUE TITLE
[global tool] FAKE dotnet global tool is not found on `zsh`

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#1951] opened 2018-05-21 14:07 UTC
### Description

When using `zsh` the `fake` global tool stub is never run, despite the appropriate `$PATH` entries being in place. The tool is run correctly using bash.  This is something that impacts every dotnet sdk global tool (try `dotnet tool install -g weeknumber && weeknumber` to verify).   I'll be opening this over at the `dotnet/cli` repo as well, but wanted this here as a tracking issue.

### Repro steps

Please provide the steps required to reproduce the problem:

0. Have the 2.1 preview SDK installed (2.1.300-rc1-008673)
1. run zsh with no profile via `zsh --no-rcs`
2. `dotnet tool install -g fake-cli --version '5.0.0-*'`
3. `fake`

### Expected behavior

The FAKE cli help should display

### Actual behavior

The shell reports that `fake` could not be found.

### Known workarounds

* run the command in bash, or
* run the fake command explicitly, via `~/.dotnet/tools/fake`

### Related information 

* Mac OSX High Sierra 10.13.4
* 5.0 rc 15
* Mono 5.12 or dotnet sdk 2.1.300-rc1-008673

**Comment by baronfel** [comment] 2018-05-21 14:11
Here's the upstream tracking issue: https://github.com/dotnet/cli/issues/9321

**Comment by matthid** [comment] 2018-05-21 14:46
@baronfel Is your shell broken? dotnet sdk is just adding an executable into the folder. afaik there is nothing specific to why is wouldn't work in zsh

**Comment by matthid** [comment] 2018-05-21 14:51
Maybe zsh doesn't resolve `~/`?

**Comment by baronfel** [comment] 2018-05-21 17:47
that's the problem exactly. that ~-path is being written by the dotnet cli tool installer, so I'm hoping they'll update and write the full path to support more shells.

**Comment by matthid** [comment] 2018-05-21 17:59
I'm closing this here since it is easy to workaround (just manually edit your PATH) and the issue is tracked in dotnet/cli

**Closed by matthid** 2018-05-21 17:59 UTC
