### ISSUE TITLE
Open System causes error in intellisense in Ionide

### ISSUE THREAD

**Issue by gkonterman** [fsharp/FAKE#1985] opened 2018-06-07 13:26 UTC
I am not sure if this is a FAKE or Ionide issue but I will report it here.

After my upgrade to FAKE 5 RTM, I get the error 

```
The type 'IEquatable`1' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

This happens when you use the `open System` statement.

I have cleaned everything (according to me). 

Small repro:

`paket.dependencies`
```
group tools
    source https://api.nuget.org/v3/index.json
    storage: none
    framework: netstandard2.0

    clitool dotnet-fake

group netcorebuild
    source https://api.nuget.org/v3/index.json
    storage: none
    framework: netstandard2.0

    nuget Fake.BuildServer.TeamCity
    nuget Fake.BuildServer.GitLab
    nuget Fake.Core.CommandLineParsing
    nuget Fake.Core.Target
    nuget Fake.DotNet.AssemblyInfoFile
    nuget Fake.DotNet.MSBuild
    nuget Fake.DotNet.Nuget
    nuget Fake.Tools.Git
    nuget Paket.Core
```

`paket.references`
```
group tools
    dotnet-fake
```

`build.fsx`
```
#r "paket: groupref netcorebuild //"
open Paket
#load "./.fake/build.fsx/intellisense.fsx"

open System <-- Error here
```

![image](https://user-images.githubusercontent.com/7427231/41102385-0fab675e-6a67-11e8-8191-bd22e7e23a11.png)

`dotnet install`
```
echo == Install .NET Core SDK

REM Install .NET Core (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Channel Current" > %output%
if errorlevel 1 goto :error
```

**Comment by matthid** [comment] 2018-06-07 15:14
Duplicate of https://github.com/fsharp/FAKE/issues/1938

Workaround is:
```fsharp
#if !FAKE
  #r "netstandard"
#endif
```

**Closed by matthid** 2018-06-07 15:14 UTC

**Comment by JarnoNijboer** [comment] 2018-06-07 21:10
Is it an option for Fake to always add a reference to `netstandard` in `intellisense.fsx`? If I'm correct it does it for several `.net fx` libraries as wel.

**Comment by matthid** [comment] 2018-06-07 21:21
@JarnoNijboer Yes that logic is part of paket, question is why it doesn't work already and how to detect if we need one. I guess this in a issue in paket load script generation as well. I'm just too lazy to reproduce it ...

So we need to fix this in paket and then the solution will flow to fake with next update
