### ISSUE TITLE
Absolute script path on linux

### ISSUE THREAD

**Issue by drauly** [fsharp/FAKE#1780] opened 2018-02-09 10:01 UTC
Hello,

### Description

I have built a docker image with fake 5 installed and it works fine. I recently upgrade to 5.0.0-beta013, and I'm not able to run script with absolute path anymore (it used to work on beta010)

### Repro steps

install fake on ubuntu in /fake, add it in PATH
copy my script (bg.fsx) on /fs
build agent run my docker image with working directory /build/myproject
run command ```fake run /fs/bg.fsx```
fake fails with error :
```
Script failed with
-> Compilation failed:
   /fs/blueGreen.fsx (1,0)-(5,22): Error FS0078: Unable to find the file 'paket:
       source https://nuget.org/api/v2
       nuget Fake.Core.Target prerelease
       nuget Fake.Core.Process prerelease
       nuget FSharp.Data' in any of
    /root/.nuget/packages/netstandard.library/2.0.0/build/netstandard2.0/ref
    /
    /root/.nuget/packages/fsharp.core/4.3.3/lib/netstandard1.6
```
If I run with relative path for the script : ```fake run ../../fs/bg.fsx``` => OK

Problem is that I can't be sure of my current working directory so I need to be able to specify script path with absolute path.

Also, I noticed that absolute path works on Windows

### Known workarounds

Work with relative path, but I said, I fill not confident with it.

### Related information 
* Ubuntu 
* No dotnet installed

Do you have any idea what' going on ? 

Thank you

**Comment by matthid** [comment] 2018-02-09 10:23
> Do you have any idea what' going on ?

Not directly. Can you try to change 

```fsharp
#r "paket:
source https://nuget.org/api/v2
nuget Fake.Core.Target prerelease
nuget Fake.Core.Process prerelease
nuget FSharp.Data"
```

(assuming from the error message)

to
```fsharp
#r "paket:
source https://nuget.org/api/v2
nuget Fake.Core.Target prerelease
nuget Fake.Core.Process prerelease
nuget FSharp.Data //"
```

(note the additional `//` at the end).
Also if this works I think you can remove the `source` line completely.

If this is indeed the problem I have no idea why a relative path would work :/

**Comment by drauly** [comment] 2018-02-09 11:27
Thank you for the quick answer @matthid,

Indeed adding the "//" works. I feel more comfortable with this solution. Will you try to spot the root cause ?

Thanks again

**Comment by matthid** [comment] 2018-02-09 11:31
If this works I kind of know what the root cause is: It is the F# compiler emitting an error. It "should" be fixed once FST-1027 is officially supported. I'm afraid that this is nothing we can (reasonably) handle within FAKE.

**Comment by drauly** [comment] 2018-02-09 11:32
Ok, so I guess we can close the issue :)

**Comment by matthid** [comment] 2018-02-09 11:32
Maybe we should report this interesting side effect to the F# compiler (but I fear that they will fix it to always emit an error which makes the current FAKE implementation completely unusable). 

/cc @forki should we report it?

**Comment by matthid** [comment] 2018-02-18 00:47
Ok reported this inconsistency upstream.

**Closed by matthid** 2018-02-18 00:47 UTC
Labels: bug, extern
