### ISSUE TITLE
Using inline paket dependencies results in assembly-not-found for paket text on Unix

### ISSUE THREAD

**Issue by dsyme** [fsharp/FAKE#2289] opened 2019-04-11 21:55 UTC
### Description

Using `#r "paket:..."` inline paket code doesn't seem to result in these being stripped out of the actual script passed to F# for execution.

### Repro steps

1. `dotnet tool install fake-cli --tool-path .fake --version 5.12.6`
2. Create `a.fsx` containing

```
#r "paket:
nuget FsLexYacc.Runtime
"
```

3. `.fake/fake run a.fsx`

Expect: runs, doing nothing

Actual: 
```
root@1a1e11a9c393:/home/tmp# .fake/fake run a.fsx
Updating group Main in /home/tmp/.fake/a.fsx/paket.dependencies
Resolving packages for group Main:
 - FsLexYacc.Runtime 8.0.1
 - FSharp.Core 4.6.2
Locked version resolution written to /home/tmp/.fake/a.fsx/paket.lock
Starting full restore process.
Script is not valid:
        /home/tmp/a.fsx (1,0)-(3,1): Error FS0078: Unable to find the file 'paket:
        nuget FsLexYacc.Runtime
        ' in any of
         /root/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref
         /home/tmp
         /home/tmp/.fake/.store/fake-cli/5.12.6/fake-cli/5.12.6/tools/netcoreapp2.1/any/
```

Notes:
* The `Unable to find the file` F# error seems to indicate that it's trying to actually run the `#r "paket: ..."` as an F# DLL reference. 
* The corresponding steps work on Windows.  
* I've tried to find the place in the FAKE source that strips out the `#r "paket:..."` to produce a new script but I can't find it.
* I thought it might be line endings, but I've tried both `dos2unix` and `unix2dos` on the file and it hasn't helped

### Related information 

* Operating system: Linux docker

**Comment by dsyme** [comment] 2019-04-11 22:15
Closing as you need to use the magic closing `//"` - where is this documented?  I stumbled across it in another bug entry
```
#r "paket:
nuget FsLexYacc.Runtime //"
```

**Comment by matthid** [comment] 2019-04-11 23:03
Yes, this is currently "by design" due to how the F# compiler handles those strings differently on Linux and windows. Ending with `//` is the only cross-platform way I have found to tell the compiler that the string is not a valid file path and emit a warning (which is ignored in FAKE).
As you have seen `#r "paket: nuget FsLexYacc.Runtime"` is a valid file path on Linux which doesn't exist hence the error.

**Comment by matthid** [comment] 2019-04-11 23:07
By the way: I think I have opened an issue or commented on an existing one in visualfsharp about this. I'm open for other suggestions but that we do not "modify" the script before "giving it" to the F#-compiler is currently by design.

**Comment by dsyme** [comment] 2019-04-12 19:27
Thanks, I understand now :) I assumed you were filtering the script! Very cunning

I do recommend you add a test case to core F# tooling to check that this remains an error not a warning.  Also perhaps we could add a warning to FAKE if the name is valid, telling to add the "//"

**Comment by matthid** [comment] 2019-04-12 19:34
> I do recommend you add a test case to core F# tooling to check that this remains an error not a warning. 

I think it should be the reverse. We should consider downgrading a not-existing file to a warning. This way it would be consistent. It doesn't make a lot of sense to only warn on one platform but fail on another.

**Comment by dsyme** [comment] 2019-04-12 19:36
sorry I meant: "I do recommend you add a test case to core F# tooling to check that this remains a warning not an error."

> I think it should be the reverse. 

The initial thing would be to pin down existing behaviour so we don't mess you

**Comment by matthid** [comment] 2019-04-12 19:40
Not sure how long the test is valid considering the work on the `#r "paket: ..."` feature.  I expect some changes will be needed in FAKE after that anyway. But good point.

**Comment by matthid** [comment] 2019-04-12 20:03
Anyway, I see this as an external quirk in the compiler itself, and I reported this over a year ago here: https://github.com/Microsoft/visualfsharp/issues/4362
Therefore I'm closing this. Please feel free to suggest otherwise ;)

**Closed by matthid** 2019-04-12 20:03 UTC
