### ISSUE TITLE
Fake.build docsite uses current sources, not the released version

### ISSUE THREAD

**Issue by charlieturndorf** [fsharp/FAKE#2263] opened 2019-02-26 21:35 UTC
### Description
When viewing the FAKE 5 documentation at fake.build, I expect to see documentation for the currently released version of FAKE. Instead, the docs are generated for the current source version. This causes frustration when attempting to use a documented feature that hasn't actually been released.

### Repro steps

1. Ensure the latest version of FAKE is installed via `dotnet tool update fake-cli -g` or similar

1. Go to https://fake.build/apidocs/v5/fake-dotnet-dotnet-buildoptions.html

2. See there is a documented BuildOptions record label called NoRestore

4. In a FAKE script, try to set BuildOptions.NoRestore on an existing record via `{ bOpt with NoRestore = true }`

### Expected behavior

Since the documentation says BuildOptions.NoRestore exists, it should.

### Actual behavior

1. `Error FS1129: The record type 'DotNet.BuildOptions' does not contain a label 'NoRestore'.`
2. Click the docsite's github link https://github.com/fsharp/FAKE/blob/master/src/app/Fake.DotNet.Cli/DotNet.fs#L1265-1265
3. See the source for NoRestore is there
4. Click History
5. See the changeset adding NoRestore hasn't been released

### Related Information
* FAKE 5

**Comment by matthid** [comment] 2019-02-26 22:17
> Instead, the docs are generated for the current source version.

I don't think that's what you are seeing.

This thing was released with 5.12.1 https://github.com/fsharp/FAKE/commit/15cb934e9c4f774fa1627bb43f8237d4aa36ee11

And 5.12.1 is the current stable release as 5.12.2 failed in the production step earlier today.
In fact you can see in the footer of the documentation that the docs are for 5.12.1 which is the current stable release.

Are you sure you have updated everything and not running from a cached compilation or something like that? Note that you need to update your packages in the build, updating the runner alone is not enough!

**Comment by matthid** [comment] 2019-02-26 22:57
Just to be absolutely sure this has been released I checked with dotpeek:

![image](https://user-images.githubusercontent.com/1866463/53452581-f4637000-3a21-11e9-928e-8c8d91881928.png)

Please feel free to open another issue or re-open if you can clarify what the issue is or if you have questions :)

**Closed by matthid** 2019-02-26 22:57 UTC

**Comment by charlieturndorf** [comment] 2019-02-27 01:36
Ah of course! Thank you!

I don't know why I assumed updating the global cli tool would update my
local dependencies. Running `paket update` fixed my issue.
