### ISSUE TITLE
Fake.Deploy call fake.exe instead of fsi

### ISSUE THREAD

**Issue by koenmetsu** [fsharp/FAKE#934] opened 2015-09-01 12:11 UTC
For Fake.Deploy, an fsx script found in the root of the package is called after deployment using `fsi.exe`. 

Given that we're using Fake.Deploy, we have access to `fake.exe` as well, right? Would it then make sense to use `fake.exe` instead of `fsi.exe` to call the fsx file?

This would enable us to re-use the Fake goodness in "deploy" scripts.

**Comment by seburgi** [comment] 2016-09-22 15:30
That would be a much appreciated improvement. I tried to use FAKE in my deploy.fsx anyway by referencing it like

    #I @"d:\tools\fake"
    #r "FakeLib.dll"

This seemed to work fine until I realized that the exit code of fsi.exe was always 0 even when a target failed, resulting in successful deployments. I guess this has to do with how FAKE handles errors internally.

**Comment by matthid** [comment] 2017-05-07 01:57
Duplicate of https://github.com/fsharp/FAKE/issues/733

**Closed by matthid** 2017-05-07 01:57 UTC
Labels: enhancement
