### ISSUE TITLE
FAKE bootstrap does not work with paths containing spaces+unicode characters

### ISSUE THREAD

**Issue by MikaelUmaN** [fsharp/FAKE#2054] opened 2018-08-05 15:14 UTC
### Description

In trying to follow the steps here: https://fake.build/fake-template.html , I receive an error and the fake-cli cannot be installed.

### Repro steps

Run:

1.` dotnet new -i "fake-template::*"`
2. `dotnet new fake`
3. `.\fake.cmd build`

in the path: C:\Users\Mikael Öhman\Programming\ReproduceScaffold

### Expected behavior

FAKE installs fake.exe in folder .fake.

### Actual behavior

Following output is encountered:
```

PS C:\Users\Mikael Öhman\Programming\ReproduceScaffold> .\fake.cmd build

C:\Users\Mikael Öhman\Programming\ReproduceScaffold>SET TOOL_PATH=.fake

C:\Users\Mikael Öhman\Programming\ReproduceScaffold>IF NOT EXIST ".fake\fake.exe" (dotnet tool install fake-cli --tool-path ./.fake --version 5.* )
**MSBUILD : error MSB1006: Property is not valid.
Switch: hman\Programming\ReproduceScaffold\.fake\.store\.stage\scmgilqi.st0
For switch syntax, type "MSBuild /help"**
The tool package could not be restored.
Tool 'fake-cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

C:\Users\Mikael Öhman\Programming\ReproduceScaffold>".fake/fake.exe" build
'".fake/fake.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

### Known workarounds

Use other bootstrap methods such as "none", and use a global install of fake cli. Or, install fake cli by setting the toolpath in a relative way, not referencing the problematic characters (Ö) and spaces.

### Related information 

* Windows
* Latest release
* .NET Core 2.1.302
* Low
* 5.X

**Comment by matthid** [comment] 2018-08-05 15:28
Yes it looks like there is a bug in the template, or in the shell scripts to be exact

**Comment by matthid** [comment] 2018-08-05 15:30
Also I noticed that we still install version 5.0.0 of the runtime because we have `--version 5.*` I expect the latest template to install the latest stable (which is 5.3 at the time). Let me take a look.

/cc @kblohm

**Comment by matthid** [comment] 2018-08-05 15:38
Looks like you found two bugs:

One is that in the `.sh` script there are indeed quotes missing.
The other one is not our bug (and the fake.cmd script looks correct to me) and reproduces on the following command line:

```cmd
matth@DESKTOP-FQBAN56 E:\Projects\FAKE\temp\Mikael Öhman\Reproduce
$ dotnet tool install fake-cli --tool-path ./.fake --version 5.*
MSBUILD : error MSB1006: Property is not valid.
Switch: hman\Reproduce\.fake\.store\.stage\24kqfmg2.aq2
For switch syntax, type "MSBuild /help"
The tool package could not be restored.
Tool 'fake-cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool
```

Can you please report this to the dotnet sdk repository?

Also we cannot workaround as `dotnet tool install fake-cli --tool-path "E:\Projects\FAKE\temp\Mikael Öhman\Reproduce\.fake" --version 5.*` yields the same error

**Comment by MikaelUmaN** [comment] 2018-08-05 18:33
Thanks for quick response and investigation. Will link to this in that repo.

**Comment by matthid** [comment] 2018-08-27 20:00
I'm closing this since it is external and already fixed.

**Closed by matthid** 2018-08-27 20:00 UTC
Labels: extern
