### ISSUE TITLE
DotNetCli and Shell.Exec are not unifed

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1760] opened 2018-01-21 13:37 UTC
### Description

The function signatures differ in how they accept parameters.

One of them requires manual escaping of values (.Net Core CLI)

### Repro steps

Example:

<img width="485" alt="screen shot 2018-01-21 at 14 34 51" src="https://user-images.githubusercontent.com/193115/35194733-5f1573a4-feb8-11e7-97bf-e21b5bb159a1.png">

### Expected behaviour

Exec-function parameters should be unified and without discrepancy.

Exec-function parameters should be passed to the kernel call to execute without requiring manual escaping from F#, by using F# types (strings, arrays, etc)

### Actual behavior

The contrary.

### Known workarounds

Manual escaping, "knowing the API", googling around.

**Comment by matthid** [comment] 2018-01-21 13:46
I *Think* I know what you mean. One problem is however that we ultimately use the `Process.Start` API which (I think by design) uses Windows cmd semantics both on windows and and other platforms. So we would need to convert everything around multiple times to get what you want. An easier way is to tell users that we have windows cmd semantics ;).

If the above doesn't make any sense then I might not get the issue... In that case please try to clarify :)

**Comment by matthid** [comment] 2018-01-21 14:52
Basically yes, however it is very well defined how they handle parsing - even if it is weird. Therefore I don't agree that p/invoke is the solution. It will bring lots of other problems (ie. APIs behaving even more different). Currently at least your code behaves the same on all platforms which is already a huge win and should not be given up easily by using p/invoke.

Instead I think internal conversations make the most sense. In fact I have written several "slim" wrappers on top of Process.Start already. For example: https://github.com/matthid/ClusterManagement/blob/master/ClusterManagement/RawProc.fs
Basically when solving this problem you need to take into consideration various implementations which behave slightly different:
 - Mono on Unix https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/eglib/src/gshell.c#L32-L104
 - .NET Framework https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx
 - .NET Core on Windows (I think it is similar to full framework)
 - .NET Core on Linux  https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L443-L522

Ideally user-code should never have workarounds like this: https://github.com/fsharp/FAKE/pull/1281/commits/285e585ec459ac7b89ca4897d1323c5a5b7e4558

P/invoke only introduces yet another implementation :/.

The idea should be to have a working baseline for everything, you can easily put a layer on top of that behaving like the unix syscall...

**Comment by matthid** [comment] 2018-05-22 22:29
PR is welcome. I'm closing this to clean the house a bit - But I assume nobody will fix the legacy API anyway ;)

**Closed by matthid** 2018-05-22 22:29 UTC
Labels: Obsolete, bug, help wanted
