### ISSUE TITLE
false nuget error in build

### ISSUE THREAD

**Issue by tigerclawn82** [fsharp/FAKE#1347] opened 2016-08-05 18:46 UTC
### Description

Fake is giving false build errors
### Repro steps
1. Minimal solution
2. build.bat/build.fsx with RestorePackages()
### Expected behavior

Solution should be build without error.
### Actual behavior

It is giving 
### Related information
- Windows Server 2016 TP5
- Stable
- .NET 4.5

```
Checking Paket version (downloading latest stable)...
Paket.exe 3.11.1 is up to date.
Paket version 3.11.1.0
Skipping resolver for group Main since it is already up-to-date
E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\paket.lock is already up-to-date
2 seconds - ready.
Paket version 3.11.1.0
Resolving packages for group Main:
 - Topshelf 3.3.1
 - FAKE 4.36.0
E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\paket.lock is already up-to-date
6 seconds - ready.
E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\tools\NuGet\nuget.exe  "install" "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.Service\packages.config" "-OutputDirectory" "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages"
Feeds used:
  C:\Users\Administrator\AppData\Local\NuGet\Cache
  C:\Users\Administrator\.nuget\packages\
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

All packages listed in E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.Service\packages.config are already installed.
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== Clean

The resulting target order is:
 - Clean
 - Build
Starting Target: Clean
Deleting contents of ./build
Finished Target: Clean
Starting Target: Build (==> Clean)
Building project: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.sln
  C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe  "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.sln" /t:Build /m      /p:RestorePackages="False" /p:OutputPath="E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"e:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\FAKE\tools\FakeLib.dll"
C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe  "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.sln" /t:Build /m      /p:RestorePackages="False" /p:OutputPath="E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"e:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 8/5/2016 11:38:07 AM.
     1>Project "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.sln" on node 1 (Build target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Any CPU".
     1>Project "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.sln" (1) is building "E:\VisualStudio
       -Bkp\Visual Studio 2015\Projects\Migrator\Migrator.Service\Migrator.Service.csproj" (2) on node 1 (default targe
       ts).
     2>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect t
       o the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       _CopyFilesMarkedCopyLocal:
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\paket-files\192.168.0.112\Core.dll
         " to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Core.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\paket-files\192.168.0.112\Logging.
         dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Logging.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.Owin.3.0.1\lib\
         net45\Microsoft.Owin.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.dl
         l".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.Owin.Host.HttpL
         istener.3.0.1\lib\net45\Microsoft.Owin.Host.HttpListener.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Proje
         cts\Migrator\build\Microsoft.Owin.Host.HttpListener.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.Owin.Hosting.3.
         0.1\lib\net45\Microsoft.Owin.Hosting.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\M
         icrosoft.Owin.Hosting.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Newtonsoft.Json.9.0.1\lib
         \net45\Newtonsoft.Json.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Newtonsoft.Json
         .dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\paket-files\192.168.0.112\Oracle.D
         ataAccess.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Oracle.DataAccess.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Owin.1.0\lib\net40\Owin.d
         ll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Owin.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.AspNet.WebApi.C
         lient.5.2.3\lib\net45\System.Net.Http.Formatting.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migr
         ator\build\System.Net.Http.Formatting.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.AspNet.WebApi.C
         ore.5.2.3\lib\net45\System.Web.Http.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Sy
         stem.Web.Http.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.AspNet.WebApi.O
         win.5.2.3\lib\net45\System.Web.Http.Owin.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\bui
         ld\System.Web.Http.Owin.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Topshelf.3.3.1\lib\net40-
         full\Topshelf.dll" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Topshelf.dll".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.Owin.3.0.1\lib\
         net45\Microsoft.Owin.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.xm
         l".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.Owin.Host.HttpL
         istener.3.0.1\lib\net45\Microsoft.Owin.Host.HttpListener.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Proje
         cts\Migrator\build\Microsoft.Owin.Host.HttpListener.xml".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.Owin.Hosting.3.
         0.1\lib\net45\Microsoft.Owin.Hosting.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\M
         icrosoft.Owin.Hosting.xml".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Newtonsoft.Json.9.0.1\lib
         \net45\Newtonsoft.Json.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Newtonsoft.Json
         .xml".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.AspNet.WebApi.C
         lient.5.2.3\lib\net45\System.Net.Http.Formatting.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migr
         ator\build\System.Net.Http.Formatting.xml".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.AspNet.WebApi.C
         ore.5.2.3\lib\net45\System.Web.Http.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Sy
         stem.Web.Http.xml".
         Copying file from "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\packages\Microsoft.AspNet.WebApi.O
         win.5.2.3\lib\net45\System.Web.Http.Owin.xml" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\bui
         ld\System.Web.Http.Owin.xml".
       _CopyAppConfigFile:
         Copying file from "App.config" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Migrator.Ser
         vice.exe.config".
       CopyFilesToOutputDirectory:
         Copying file from "obj\Release\Migrator.Service.exe" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migra
         tor\build\Migrator.Service.exe".
         Migrator.Service -> E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Migrator.Service.exe
         Copying file from "obj\Release\Migrator.Service.pdb" to "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migra
         tor\build\Migrator.Service.pdb".
     2>Done Building Project "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.Service\Migrator.Servic
       e.csproj" (default targets).
     1>Done Building Project "E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\Migrator.sln" (Build target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.61
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Core.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Logging.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.Host.HttpListener.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.Host.HttpListener.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.Hosting.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.Hosting.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Microsoft.Owin.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Migrator.Service.exe
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Migrator.Service.exe.config
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Migrator.Service.pdb
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Newtonsoft.Json.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Newtonsoft.Json.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Oracle.DataAccess.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Owin.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\System.Net.Http.Formatting.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\System.Net.Http.Formatting.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\System.Web.Http.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\System.Web.Http.Owin.dll
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\System.Web.Http.Owin.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\System.Web.Http.xml
Build-Output: E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build\Topshelf.dll
Finished Target: Build

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0199608
Build      00:00:01.0668864
Total:     00:00:01.1861386
Status:    Ok
---------------------------------------------------------------------
System.Exception: Start of process E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@79-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 79
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 79
   at Fake.RestorePackageHelper.runNuGet(String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 86
   at Fake.RestorePackageHelper.runNuGetTrial@94.Invoke(Unit unitVar0) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 94
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.RestorePackageHelper.runNuGetTrial(Int32 retries, String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 95
   at Fake.RestorePackageHelper.RestorePackage(FSharpFunc`2 setParams, String packageFile) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 154
   at Fake.RestorePackageHelper.RestorePackages@161-1.Invoke(String packageFile) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 161
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in E:\VisualStudio-Bkp\Visual Studio 2015\Projects\Migrator\build.fsx:line 5
Stopped due to error
```

Thanks

**Comment by theprash** [comment] 2016-08-16 13:59
I've been seeing false errors occasionally too. They seem to be real errors that occurred previously but are cached in the `.fake` folder somehow. Try renaming that folder to see if the error goes away. Hang on to it though because it might be a useful repro case. Can you upload the whole build folder, script and `.fake` folder somewhere?

**Comment by matthid** [comment] 2017-05-07 00:49
Yes steps to reproduce would be appreciated... Closing for now.

**Closed by matthid** 2017-05-07 00:49 UTC
