### ISSUE TITLE
CI with Fake 5 dotnet Install problem

### ISSUE THREAD

**Issue by talajiam** [fsharp/FAKE#2047] opened 2018-07-31 15:20 UTC
If i try to install fake 5 into a particular folder and run from CI server facing problem. saying file not found **_<c:\LocalSolutionFolder>_**\fktools\.store\fake-cli\5.3.0\fake-cli\5.3.0\tools\netcoreapp2.1\any\fake-cli.dll

Build runs perfectly fine if run from local system. 

Steps  
1) Install into custom folder "fktools"
dotnet tool install fake-cli --tool-path fktools

2) Run build.fsx
 .\fktools\Fake.exe  run .\build.fsx 

Error message i get on Build Agent 
The application to execute does not exist: "**_<c:\LocalSolutionFolder>_**\fktools\.store\fake-cli\5.3.0\fake-cli\5.3.0\tools\netcoreapp2.1\any\fake-cli.dll"

**Comment by matthid** [comment] 2018-07-31 16:17
Does this happen on all fake versions or only 5.3?

**Comment by matthid** [comment] 2018-07-31 16:28
Can you give more details like `dotnet --version`, general information about your environment?

Can you try to move your `c:\LocalSolutionFolder` to something like `C:\Test` maybe you have reached the MAX_PATH limit somehow?

`fktools\.store\fake-cli\5.3.0\fake-cli\5.3.0\tools\netcoreapp2.1\any\fake-cli.dll` should actually exist after installing the tool. Can you look at the explorer what you have there?

Also I noticed the path `"<c:\LocalSolutionFolder>\fktools.store\fake-cli\5.3.0\fake-cli\5.3.0\tools\netcoreapp2.1\any\fake-cli.dll"` it should be `fktools\store` is that some copy paste error or is the path indeed wrong?

**Comment by talajiam** [comment] 2018-08-01 06:58
thanks for reply. 

dotnet --version =2.1.302

I tried to rename my local folder from <c:\LocalSolutionFolder> to <c:\LocalSolutionFolder1> and i start getting same error in local; "<c:\LocalSolutionFolder>\fktools.store\fake-cli\5.3.0\fake-cli\5.3.0\tools\netcoreapp2.1\any\fake-cli.dll"

It still keeps on searching for folder <c:\LocalSolutionFolder> instead of resolving path to  <c:\LocalSolutionFolder1>

PWD: <c:\LocalSolutionFolder1> .\fktools\fake.exe  run .\build.fsx

**Comment by matthid** [comment] 2018-08-01 07:06
can you move everything into a shorter folder path, delete the .fake directory and try again? Also can you attach the output of the tool install command?

**Comment by matthid** [comment] 2018-08-01 07:17
All I can say is that this looks like a bug in the sdk and not something we can fix here. Therefore we need a good idea of what is happening or we need to be able to reproduce it. Otherwise we will not get a fix.

Can you tell me more about the build agent environment? Do you have direct access?

**Comment by matthid** [comment] 2018-08-01 07:36
It might be that the tool installation is not “portable” instead you need to do the installation at the correct folder path. Is that what you are saying?

**Comment by talajiam** [comment] 2018-08-01 07:51
Yes.. i am trying to make it portable. so that on build agent i don't require it to install.

**Comment by matthid** [comment] 2018-08-01 17:36
You can open an issue over at the dotnet guys but I'm afraid that this currently is not a supported scenario for dotnet tool. It will work within the installed directory only.

However (if that is an viable alternative) you can download and extract the portable package from fake:

![image](https://user-images.githubusercontent.com/1866463/43538326-fa69d6ec-95c1-11e8-80d0-e00c5a0c5d19.png)

You can automate this process by generating url on the bottom.

**Comment by talajiam** [comment] 2018-08-02 10:10
Hey Thanks, for pointing out the portable version. 

It now runs build.fsx on Agent. 
But i am getting error;

**Comment by matthid** [comment] 2018-08-02 12:34
This looks more like a msbuild problem than something with fake. Maybe dotnet build does set some environment variables or does something behind the scenes

**Comment by matthid** [comment] 2018-08-04 18:50
If `dotnet build` succeeds you should consider using `DotNet.build` instead of `MSBuild.runRelease`?

**Comment by HoraceGonzalez** [comment] 2018-08-12 00:11
Not sure if this is relevant, but there seems to be an issue with dotnet sdk  2.1.300 https://github.com/dotnet/cli/issues/9319. It can't resolve relative`--tool-path` on mac and linux, and when you try to run `fake` from your tools directory, you'll see the `The application to execute does not exist` error.

The workaround is to always use an absolute tools path. Eg.

```
dotnet tool install fake-cli --tools-path $(pwd)/mytools
```

**Comment by matthid** [comment] 2018-08-12 04:27
@HoraceGonzalez can you try to set PATH manually?

**Comment by kblohm** [comment] 2018-08-12 07:43
@HoraceGonzalez I think the original issue might be related. But this should be fixed by #2014. What version of the template are you using @talajiam ?

**Comment by HoraceGonzalez** [comment] 2018-08-12 22:07
@matthid, I added my tools path to my `PATH` env var manually, confirmed that `fake` does get executed, but unfortunately the error message is the same: 
```
The application to execute does not exist: '/home/me/myproj/tools/..//home/me/myproj/tools/.store/fake-cli/5.4.0/fake-cli/5.4.0/tools/netcoreapp2.1/any/fake-cli.dll'.
```

I really think this is a dotnet cli issue, though. The workaround suggested on the github issue worked for me.

**Comment by matthid** [comment] 2018-08-27 20:02
closing since there was no more response

**Closed by matthid** 2018-08-27 20:02 UTC
Labels: Waiting for author
