### ISSUE TITLE
Running builds in verbose mode

### ISSUE THREAD

**Issue by devkhan** [fsharp/FAKE#1170] opened 2016-03-07 17:29 UTC
Is there an option to run the given build targets in verbose mode. e.g. I am trying to run unit tests which are specified using a `fake` script, so I need to see the detailed log, which test passed, failed, ignored, etc. Is there a command line argument we can pass to the build script?

**Comment by dsyme** [comment] 2016-04-14 13:34
Duplicate of https://github.com/fsharp/FAKE/issues/354

**Closed by dsyme** 2016-04-14 13:34 UTC
