### ISSUE TITLE
--single-target is not working

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#594] opened 2014-11-17 13:31 UTC
It always execute the dependencies. I have tried all possible combinations.

**Comment by cdroulers** [comment] 2015-05-13 18:38
Works for me in version 3.27.5 with both `-st` and `--single-target`

**Comment by Stift** [comment] 2015-05-28 10:30
I can confirm the problem. Normally `-st` is working, but when I define an extra build parameter it is executed in the target order and `-st` is ignored.

**Comment by hiscodeness** [comment] 2015-07-01 19:08
I confirm the problem too. Easily reproducable by calling e.g. `FAKE.exe Build -st param=1`.

**Comment by smoothdeveloper** [comment] 2015-12-22 20:12
also hitting this issue whenever I specify a parameter it ignores -st, is there a workaround?

**Comment by cdroulers** [comment] 2015-12-22 20:14
--single-target works great for me

**Comment by smoothdeveloper** [comment] 2015-12-23 02:26
@cdroulers Am I doing something wrong?

```
> build -v
FakePath: C:\work\gitsvnclone\packages\FAKE\tools\FakeLib.dll
FAKE - F# Make "4.11.0"
> build generatecode buildMode=Debug --single-target
Building project with version: LocalBuild
Shortened DependencyGraph for Target generatecode:
<== generatecode
   <== buildshared
   <== buildresources
   <== warmuplocaldatabase

The resulting target order is:
 - buildshared
 - buildresources
 - warmuplocaldatabase
 - generatecode
Starting Target: buildshared
...
```

**Comment by cdroulers** [comment] 2015-12-23 02:30
No idea. I use fake.exe and --single-target and it works. But with -st, it
doesn't work.

**Comment by mynkow** [comment] 2015-12-23 05:05
Can you hive us working sample?

-----Original Message-----

**Comment by bentayloruk** [comment] 2016-01-17 16:44
I think this will work for you if you change the command line to use the "modern" options.  Your current usage is a mix of the two.  This should work.

`.\bin\tools\FAKE\tools\Fake.exe test.fsx %TARGET% -st -ev applicationName MyApp`

There are some [docs here too](http://fsharp.github.io/FAKE/commandline.html).

**Comment by dsyme** [comment] 2016-04-14 11:24
@mynkow can we close this issue?

**Comment by smoothdeveloper** [comment] 2016-07-13 22:24
It seems #1301 will finally solve this :smile:

**Closed** 2016-07-14 08:50 UTC

**Comment by mynkow** [comment] 2016-07-19 19:20
I've just tested this. It is working now. Thank you.

**Comment by sdluxeon** [comment] 2016-07-21 18:48
That escalated quickly :smiley:
