### ISSUE TITLE
FAKE caching fails to load assembly for another target

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FAKE#1372] opened 2016-09-06 17:56 UTC
I think I finally understood one issue that I've seen every now and then in FsLab.
### How to reproduce
1. To reproduce this, download the [FsLab Journal template (ZIP)](https://github.com/fslaborg/FsLab.Templates/archive/journal.zip) and put it into some folder.
2. Run `build.cmd`. This runs the build script with the default target (which just prints some info) and saves the compiled cached build script. 
3. Then run `build.cmd html`. This should process the literate scripts and produce HTML, but instead it fails with the error:
   
   ```
   Error: System.IO.FileNotFoundException: Could not load file or assembly 
   'FSharp.Markdown, Version=2.14.4.0, Culture=neutral, PublicKeyToken=null' 
   or one of its dependencies. The system cannot find the file specified.
   File name: 'FSharp.Markdown, Version=2.14.4.0, Culture=neutral, PublicKeyToken=null'
   ```
### What goes wrong

The reason why this fails is that the default target does not force all dependencies to actually load. I never quite understood this - but even though we have `#r "FSharp.Markdown.dll"` in the script, the F# Interactive only loads the assembly when you actually use some type from it. The default target does not do this and so `FSharp.Markdown.dll` is not listed in the `.fake/build.fsx_2DCC2CF4_config.xml` file.

If you delete `.fake` folder and run `build.cmd html` as the first command, it loads the assembly, stores it in the config file and it will work again when you run `build.cmd html` again.
### Workarounds

Well, you can delete the `.fake` folder. 

I have no idea how this could be nicely solved in FAKE though. The error happens when running a target, so just blindly re-running the build script and cleaning cache might lead to inconsistent states. FAKE could register AssemblyResolve handler, but there is no way to know here to look for assemblies.

Currently, the list of assemblies is [generated here](https://github.com/fsharp/FAKE/blob/1277af1f0a03700040e12bc10c1f964c19de6614/src/app/FakeLib/FSIHelper.fs#L396) based on the assemblies loaded at runtime - but this may be wrong if some assemblies were referenced, but not actually loaded. I guess we could try extracting all `#r` (which [already happens here](https://github.com/fsharp/FAKE/blob/1277af1f0a03700040e12bc10c1f964c19de6614/src/app/FakeLib/FSIHelper.fs#L69)) and append them to the ones loaded at runtime?

**Comment by forki** [comment] 2016-09-07 08:43
cc @matthid

**Comment by matthid** [comment] 2016-09-07 09:16
This is sadly by design and just the way it works right now.

vnext will not have this limitation as you'll specify allyou dependencies (see my coreclr branch).

this issue would be a reason to backport the new stuff (for which I did not saw a good reason until now)

**Comment by matthid** [comment] 2016-09-07 09:17
Workaround for now: Try to force load the assembly always with assembly.load

**Comment by matthid** [comment] 2016-09-07 09:18
parsing '#r' lines is not a complete solution either as there are always cases we don't get...

**Comment by tpetricek** [comment] 2016-09-07 12:35
@matthid Do you have a link to an example involving "specify all your dependencies explicitly"? This sounds a bit scary for FsLab, which has a bit too many dependencies :)

**Comment by matthid** [comment] 2016-09-07 12:54
With vnext I mean https://github.com/fsharp/FAKE/pull/1281. There are already docs linked...

```
(* -- Fake Dependencies paket-inline
source http://nuget.org/api/v2

nuget FsLab
-- Fake Dependencies -- *)
#load "./.fake/build.fsx/loadDependencies.fsx"
```

**Comment by matthid** [comment] 2016-09-22 18:08
Hm, I'll start to backport in order to solve this issue. But now I remember why I didn't do it in the first place....

@forki it will introduce `Paket.Core` as dependency of FAKE and increase the download size of FAKE.

**Comment by matthid** [comment] 2017-05-01 01:30
This should work with https://github.com/fsharp/FAKE/pull/1281 (see [fake-dotnetcore](https://github.com/matthid/FAKE/blob/coreclr/help/fake-dotnetcore.md) and [migrate-to-fake-5](https://github.com/matthid/FAKE/blob/coreclr/help/migrate-to-fake-5.md)), at least in the netcore FAKE 5 version.

It is still an early alpha and only works with netcore compatible packages obviously. I decided against the backport since my last comment. It will produce too much headaches. We already have (imho) a good migrations path, so ...

Like said the workaround is to use all required stuff at the start of the script or load it explicitly via `Assembly.Load`

**Comment by matthid** [comment] 2017-05-07 00:56
Closing this as by-design. 
- There is a workaround to disable cache. 
- There is a workaround to explicitly load the missing assemblies
- Once we have stuff migrated to netcore, FAKE5 should solve these kind of problems.

**Closed by matthid** 2017-05-07 00:56 UTC
