### ISSUE TITLE
Error when invoking fake run with different casings

### ISSUE THREAD

**Issue by nikolamilekic** [fsharp/FAKE#2314] opened 2019-05-09 11:29 UTC
### Description

I got the following error so I'm opening an issue as requested.

CACHING WARNING
this might happen after Updates...
please open a issue on FAKE and /cc @matthid ONLY IF this happens reproducibly)

Error: System.Exception: We could not find a type similar to '<StartupCode$Hello_39CC74F39529626A47F150CE9573BBEA9E7A121F27DB517781F4AAE80B07F7A3>.$Hello$fsx' containing a 'main@' method in the cached assembly (D:\projects\Scripts\.fake\Hello.fsx\Hello_39CC74F39529626A47F150CE9573BBEA9E7A121F27DB517781F4AAE80B07F7A3.dll)!
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in D:\a\1\s\src\app\Fake.Runtime\YaafFSharpScripting.fs:line 1242
   at Fake.Runtime.CompileRunner.tryRunCached(CoreCacheInfo c, FakeContext context) in D:\a\1\s\src\app\Fake.Runtime\CompileRunner.fs:line 47
   at Fake.Runtime.CompileRunner.runFakeScript(FSharpOption`1 cache, FakeContext context) in D:\a\1\s\src\app\Fake.Runtime\CompileRunner.fs:line 155
Script is not valid:
        commandLineArgs (0,0)-(0,0): Error FS2014: A problem occurred writing the binary 'D:\projects\Scripts\.fake\Hello.fsx\Hello_39CC74F39529626A47F150CE9573BBEA9E7A121F27DB517781F4AAE80B07F7A3.dll': Could not open file for writing (binary mode): D:\projects\Scripts\.fake\Hello.fsx\Hello_39CC74F39529626A47F150CE9573BBEA9E7A121F27DB517781F4AAE80B07F7A3.dll

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a script called hello.fsx

2. fake run hello.fsx

3. fake run Hello.fsx (capital H!)

### Expected behavior

No error.

### Actual behavior

The error.

### Known workarounds

Correct capitalization.

### Related information 

* Operating system: Win10
* Version of FAKE (4.X, 5.X): 5.13.5

**Comment by matthid** [comment] 2019-05-09 11:37
Very nice find, thanks for reporting and the steps

**Comment by matthid** [comment] 2019-05-09 11:42
This are actually two bugs:

- I think what happens is that FAKE detects something is wrong with the cache and tries to recompile. However the assembly has already been loaded and is "locked", we probably need to "unload" the Assembly Context such that the file-lock disappears and the compilation succeeds.

- Fake should realize on windows that it doesn't need to recompile stuff if only casing changed. 

Imho the first bug should be fixed first. The second is more an enhancement (and a bit of ugliness), but not really a problem.

**Closed** 2019-06-09 13:22 UTC
Labels: bug

**Comment by Thorium** [comment] 2024-09-03 18:25
I'm facing similar error with FAKE 6.1.1 when trying to run on .NET 8 globals.json, and the issue is probably that .NET compiles a  build.fsx to a temporary dll under .fake directory, but then because it's .NET 8 dll, then FAKE (build with .NET 6) cannot read it properly and doesn't find the entry-point `@main` to the program (even when it actually is there if you look by IlSpy).

**Comment by xperiandri** [comment] 2024-09-03 19:09
If you want to migrate everything to .NET 8, I support
